apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: pod-a
spec:
  containers:
  - name: container-a
    image: hashicorp/http-echo
    args:
      - "-text=Hello from pod-a"
    ports:
    - containerPort: 5678
