apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: simple-api-login
        image: techwithadedayo/simple-login-api:10
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://host.docker.internal:27017"
        - name: JWT_SECRET
          value: "your_super_secret_key"

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
  type: NodePort
