apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: [ "sh", "-c", "while true; do curl http:// 10.244.0.4:5678; sleep 5; done" ]
