apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  containers:
  - name: curl
    image: curlimages/curl
    # Insert service IP
    command: [ "sh", "-c", "while true; do curl http://10.110.129.152; sleep 5; done" ]
