apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: simple-api-login
    image: techwithadedayo/simple-login-api:v1
    ports:
    - containerPort: 5000
    env:
    - name: MONGO_URI
      value: "mongodb://host.docker.internal:27017"
    - name: JWT_SECRET
      value: "your_super_secret_key"

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80           # Service port (what clients use)
    targetPort: 5000   # Container port
    nodePort: 30080    # Optional - Kubernetes will assign one if not specified
  type: NodePort
