apiVersion: v1
kind: Pod
metadata:
  name: pod-a
spec:
  containers:
    - name: web
      image: hashicorp/http-echo
      args:
        - "-text=Hello from Pod A"
      ports:
        - containerPort: 5678
